"""Core domain models and scoring logic."""

from .models import Participant, Competition, DisciplineResult
from .scorer import compute_competition_ranks, ACC, AUS, AUS40, MTA, END, END3, FC, TC, TC50, TIMED, TAPIR
from .constants import (
    DISC_CODE_ACC,
    DISC_CODE_AUS,
    DISC_CODE_AUS40,
    DISC_CODE_MTA,
    DISC_CODE_END,
    DISC_CODE_END3,
    DISC_CODE_FC,
    DISC_CODE_TC,
    DISC_CODE_TC50,
    DISC_CODE_TIMED,
    DISC_CODE_TAPIR,
    DISC_LABEL_ACC,
    DISC_LABEL_AUS,
    DISC_LABEL_AUS40,
    DISC_LABEL_MTA,
    DISC_LABEL_END,
    DISC_LABEL_END3,
    DISC_LABEL_FC,
    DISC_LABEL_TC,
    DISC_LABEL_TC50,
    DISC_LABEL_TIMED,
    DISC_LABEL_TAPIR,
    ALL_DISCIPLINE_CODES,
    ALL_DISCIPLINE_LABELS,
)

__all__ = [
    "Participant",
    "Competition",
    "DisciplineResult",
    "compute_competition_ranks",
    "ACC",
    "AUS",
    "AUS40",
    "MTA",
    "END",
    "END3",
    "FC",
    "TC",
    "TC50",
    "TIMED",
    "TAPIR",
    "DISC_CODE_ACC",
    "DISC_CODE_AUS",
    "DISC_CODE_AUS40",
    "DISC_CODE_MTA",
    "DISC_CODE_END",
    "DISC_CODE_END3",
    "DISC_CODE_FC",
    "DISC_CODE_TC",
    "DISC_CODE_TC50",
    "DISC_CODE_TIMED",
    "DISC_CODE_TAPIR",
    "DISC_LABEL_ACC",
    "DISC_LABEL_AUS",
    "DISC_LABEL_AUS40",
    "DISC_LABEL_MTA",
    "DISC_LABEL_END",
    "DISC_LABEL_END3",
    "DISC_LABEL_FC",
    "DISC_LABEL_TC",
    "DISC_LABEL_TC50",
    "DISC_LABEL_TIMED",
    "DISC_LABEL_TAPIR",
    "ALL_DISCIPLINE_CODES",
    "ALL_DISCIPLINE_LABELS",
]
